### PR TITLE
add support for multi-threading

### PR DESCRIPTION
**Pull request by ajaech**
A new command line argument controls how many threads to use. A thread
pool is created and the main work of updating the data structures after
a cluster merge is split equally among all the threads in the pool. The
clustering can be more than 10 times as fast using multiple threads,
depending on how many cores on the CPU.

### CODE REVIEW

**Comment by arian-x** [comment]
what is the command line argument -t or ... ?! and how many threads are safe to use?!

**Comment by ajaech** [comment]
Are you asking what the command line option is to set the number of
threads? I think it is --threads. See here
<https://github.com/percyliang/brown-cluster/blob/master/wcluster.cc#L63>.

It is safe to use as many threads as you want but you will probably not get
any benefit to using more threads than there are cores on your cpu.

**Comment by arian-x** [comment]
thanks, I think adding the command line option in the Read Me would help others to understand how to use this feature.

**Comment by ajaech** [comment]
When you run the script with no arguments it should print out a list of all
the arguments along with short descrptions.

**Pull request merged**
